const express = require('express');
const eventsController = require('./../controllers/eventsController');
const router = express.Router();
const authController = require('./../controllers/authController');
router.use(authController.protect);
router.post('/', eventsController.addEvent);
router.get('/', eventsController.findAllEvents);
router.delete('/:id', eventsController.deleteEvent);
router.get('/:id', eventsController.findEventById);
router.patch('/:id', eventsController.updateEvent);
router.get('/garden/:gardenId', eventsController.findEventsInGarden);
module.exports = router;
